In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
text = ['This is a line',
       'This is another line',
       'Completely different line']

In [3]:
#Exploring count vectorisor which creates a BOW model for us 
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
#help(CountVectorizer)

In [6]:
cv = CountVectorizer()

In [8]:
sparse_matrix = cv.fit_transform(text)

In [10]:
sparse_matrix.todense() #not to use this on large data sets as takes up lots of memory 

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [11]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [12]:
#removal of stop words

In [25]:
cv1 = CountVectorizer(stop_words='english')

In [26]:
sparse_matrix = cv1.fit_transform(text)

In [27]:
sparse_matrix.todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [28]:
cv1.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

In [29]:
# now transform to a term frequency inverse document frequency vector TDIDF transformer  

In [30]:
from sklearn.feature_extraction.text import TfidfTransformer

In [31]:
tfidf = TfidfTransformer()

In [33]:
results = tfidf.fit_transform(sparse_matrix) #pass in BOW convert to TF-IDF

In [34]:
results.todense()

matrix([[0.        , 0.        , 1.        ],
        [0.        , 0.        , 1.        ],
        [0.65249088, 0.65249088, 0.38537163]])

In [39]:
#can do all of the above with .
from sklearn.feature_extraction.text import TfidfVectorizer

In [41]:
tv = TfidfVectorizer()

In [42]:
tv_results = tv.fit_transform(text)

In [43]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])